[2024-11-14T02:33:15.434+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stockprices_v2_decorator.load scheduled__2024-11-14T02:20:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
