[2024-11-19T15:49:39.788+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stockprices_v2_decorator.return_last_90d_price scheduled__2024-11-19T15:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
