[2024-11-14T02:21:12.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:21:12.167+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:21:06.072869+00:00 [queued]>
[2024-11-14T02:21:12.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:21:06.072869+00:00 [queued]>
[2024-11-14T02:21:12.208+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-14T02:21:12.257+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-11-14 02:21:06.072869+00:00
[2024-11-14T02:21:12.270+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1929) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T02:21:12.275+0000] {standard_task_runner.py:63} INFO - Started process 1939 to run task
[2024-11-14T02:21:12.296+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stockprices_v2_decorator', 'extract', 'manual__2024-11-14T02:21:06.072869+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/stockprices_v2_decorator(3).py', '--cfg-path', '/tmp/tmp0wvlwsto']
[2024-11-14T02:21:12.300+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask extract
[2024-11-14T02:21:12.475+0000] {task_command.py:426} INFO - Running <TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:21:06.072869+00:00 [running]> on host 3627cdc70e56
[2024-11-14T02:21:12.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stockprices_v2_decorator' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:21:06.072869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:21:06.072869+00:00'
[2024-11-14T02:21:12.717+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:21:12.741+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:21:12.745+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stockprices_v2_decorator(3).py", line 38, in extract
    url_template = Variable.get("url")
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable url does not exist'
[2024-11-14T02:21:12.767+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stockprices_v2_decorator, task_id=extract, run_id=manual__2024-11-14T02:21:06.072869+00:00, execution_date=20241114T022106, start_date=20241114T022112, end_date=20241114T022112
[2024-11-14T02:21:12.796+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task extract ('Variable url does not exist'; 1939)
[2024-11-14T02:21:12.826+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:21:12.983+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T02:21:12.995+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
