[2024-11-14T00:19:10.578+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T00:19:10.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PopulationDataToSnowflake.load_population_data manual__2024-11-14T00:18:30.781212+00:00 [queued]>
[2024-11-14T00:19:10.606+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PopulationDataToSnowflake.load_population_data manual__2024-11-14T00:18:30.781212+00:00 [queued]>
[2024-11-14T00:19:10.608+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T00:19:10.616+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_population_data> on 2024-11-14 00:18:30.781212+00:00
[2024-11-14T00:19:10.625+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=522) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T00:19:10.627+0000] {standard_task_runner.py:63} INFO - Started process 524 to run task
[2024-11-14T00:19:10.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'PopulationDataToSnowflake', 'load_population_data', 'manual__2024-11-14T00:18:30.781212+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/PopulationDataToSnowflake.py', '--cfg-path', '/tmp/tmp84s7rqlp']
[2024-11-14T00:19:10.633+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load_population_data
[2024-11-14T00:19:10.669+0000] {task_command.py:426} INFO - Running <TaskInstance: PopulationDataToSnowflake.load_population_data manual__2024-11-14T00:18:30.781212+00:00 [running]> on host 3627cdc70e56
[2024-11-14T00:19:10.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PopulationDataToSnowflake' AIRFLOW_CTX_TASK_ID='load_population_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T00:18:30.781212+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T00:18:30.781212+00:00'
[2024-11-14T00:19:10.762+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T00:19:10.773+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-14T00:19:10.776+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.10.25-linuxkit-aarch64-with-glibc2.36
[2024-11-14T00:19:10.781+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-14T00:19:12.280+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-14T00:19:12.542+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-14T00:23:29.493+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-14T00:23:29.515+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-14T00:23:29.529+0000] {process_utils.py:132} INFO - Sending 15 to group 524. PIDs of all processes in the group: [524]
[2024-11-14T00:23:29.533+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 524
[2024-11-14T00:23:29.537+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-14T00:23:29.554+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T00:23:29.795+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=524, status='terminated', exitcode=0, started='00:19:09') (524) terminated with exit code 0
