[2024-11-14T02:31:42.320+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stockprices_v2_decorator.load manual__2024-11-14T02:29:44.489341+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
