[2024-11-20T13:06:05.897+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stockprices_v2_decorator.extract scheduled__2024-11-20T07:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
