[2024-11-19T06:30:38.157+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stockprices_v2_decorator.extract__1 scheduled__2024-11-19T06:10:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
